/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  BondingMath,
  BondingMathInterface,
} from "../../../src/libraries/BondingMath";

const _abi = [
  {
    inputs: [],
    name: "BondingMath__DiscountExceeds100",
    type: "error",
  },
  {
    inputs: [],
    name: "BondingMath__PremiumExceeds100",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220702c2acca17a9421f8101f3aed562832cc0588afb4bb026016273b9a88248c3a64736f6c63430008180033";

type BondingMathConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BondingMathConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BondingMath__factory extends ContractFactory {
  constructor(...args: BondingMathConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BondingMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BondingMath__factory {
    return super.connect(runner) as BondingMath__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BondingMathInterface {
    return new Interface(_abi) as BondingMathInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BondingMath {
    return new Contract(address, _abi, runner) as unknown as BondingMath;
  }
}
