/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOTCSwap {
  export type PurchaseOrderStruct = {
    buyer: AddressLike;
    usdcAmount: BigNumberish;
    fvcAmount: BigNumberish;
    deadline: BigNumberish;
    nonce: BigNumberish;
  };

  export type PurchaseOrderStructOutput = [
    buyer: string,
    usdcAmount: bigint,
    fvcAmount: bigint,
    deadline: bigint,
    nonce: bigint
  ] & {
    buyer: string;
    usdcAmount: bigint;
    fvcAmount: bigint;
    deadline: bigint;
    nonce: bigint;
  };
}

export interface IOTCSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateFVCAmount"
      | "getRemainingAllocation"
      | "isEligibleToPurchase"
      | "purchaseWithMerkleProof"
      | "purchaseWithSignedOrder"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PurchaseCompleted" | "SaleConfigUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateFVCAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingAllocation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleToPurchase",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseWithMerkleProof",
    values: [BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseWithSignedOrder",
    values: [IOTCSwap.PurchaseOrderStruct, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateFVCAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleToPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseWithMerkleProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseWithSignedOrder",
    data: BytesLike
  ): Result;
}

export namespace PurchaseCompletedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    usdcAmount: BigNumberish,
    fvcAmount: BigNumberish,
    vestingScheduleId: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    usdcAmount: bigint,
    fvcAmount: bigint,
    vestingScheduleId: bigint
  ];
  export interface OutputObject {
    buyer: string;
    usdcAmount: bigint;
    fvcAmount: bigint;
    vestingScheduleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleConfigUpdatedEvent {
  export type InputTuple = [
    merkleRoot: BytesLike,
    pricePerToken: BigNumberish,
    totalCap: BigNumberish,
    individualCap: BigNumberish
  ];
  export type OutputTuple = [
    merkleRoot: string,
    pricePerToken: bigint,
    totalCap: bigint,
    individualCap: bigint
  ];
  export interface OutputObject {
    merkleRoot: string;
    pricePerToken: bigint;
    totalCap: bigint;
    individualCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IOTCSwap extends BaseContract {
  connect(runner?: ContractRunner | null): IOTCSwap;
  waitForDeployment(): Promise<this>;

  interface: IOTCSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateFVCAmount: TypedContractMethod<
    [usdcAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getRemainingAllocation: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  isEligibleToPurchase: TypedContractMethod<
    [user: AddressLike, usdcAmount: BigNumberish],
    [boolean],
    "view"
  >;

  purchaseWithMerkleProof: TypedContractMethod<
    [usdcAmount: BigNumberish, merkleProof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  purchaseWithSignedOrder: TypedContractMethod<
    [order: IOTCSwap.PurchaseOrderStruct, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateFVCAmount"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingAllocation"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isEligibleToPurchase"
  ): TypedContractMethod<
    [user: AddressLike, usdcAmount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchaseWithMerkleProof"
  ): TypedContractMethod<
    [usdcAmount: BigNumberish, merkleProof: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "purchaseWithSignedOrder"
  ): TypedContractMethod<
    [order: IOTCSwap.PurchaseOrderStruct, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PurchaseCompleted"
  ): TypedContractEvent<
    PurchaseCompletedEvent.InputTuple,
    PurchaseCompletedEvent.OutputTuple,
    PurchaseCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SaleConfigUpdated"
  ): TypedContractEvent<
    SaleConfigUpdatedEvent.InputTuple,
    SaleConfigUpdatedEvent.OutputTuple,
    SaleConfigUpdatedEvent.OutputObject
  >;

  filters: {
    "PurchaseCompleted(address,uint256,uint256,uint256)": TypedContractEvent<
      PurchaseCompletedEvent.InputTuple,
      PurchaseCompletedEvent.OutputTuple,
      PurchaseCompletedEvent.OutputObject
    >;
    PurchaseCompleted: TypedContractEvent<
      PurchaseCompletedEvent.InputTuple,
      PurchaseCompletedEvent.OutputTuple,
      PurchaseCompletedEvent.OutputObject
    >;

    "SaleConfigUpdated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      SaleConfigUpdatedEvent.InputTuple,
      SaleConfigUpdatedEvent.OutputTuple,
      SaleConfigUpdatedEvent.OutputObject
    >;
    SaleConfigUpdated: TypedContractEvent<
      SaleConfigUpdatedEvent.InputTuple,
      SaleConfigUpdatedEvent.OutputTuple,
      SaleConfigUpdatedEvent.OutputObject
    >;
  };
}
