/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IVestingVault {
  export type VestingScheduleStruct = {
    beneficiary: AddressLike;
    totalAmount: BigNumberish;
    claimedAmount: BigNumberish;
    startTime: BigNumberish;
    cliffTime: BigNumberish;
    endTime: BigNumberish;
    isRevocable: boolean;
    isRevoked: boolean;
    revoker: AddressLike;
  };

  export type VestingScheduleStructOutput = [
    beneficiary: string,
    totalAmount: bigint,
    claimedAmount: bigint,
    startTime: bigint,
    cliffTime: bigint,
    endTime: bigint,
    isRevocable: boolean,
    isRevoked: boolean,
    revoker: string
  ] & {
    beneficiary: string;
    totalAmount: bigint;
    claimedAmount: bigint;
    startTime: bigint;
    cliffTime: bigint;
    endTime: bigint;
    isRevocable: boolean;
    isRevoked: boolean;
    revoker: string;
  };
}

export interface IVestingVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateClaimableAmount"
      | "calculateVestedAmount"
      | "claimVestedTokens"
      | "createVestingSchedule"
      | "getVestingSchedule"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TokensClaimed" | "VestingScheduleCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateClaimableAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateVestedAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimVestedTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createVestingSchedule",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingSchedule",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateClaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateVestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimVestedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingSchedule",
    data: BytesLike
  ): Result;
}

export namespace TokensClaimedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    amount: BigNumberish,
    remainingAmount: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    amount: bigint,
    remainingAmount: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    amount: bigint;
    remainingAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingScheduleCreatedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    totalAmount: BigNumberish,
    startTime: BigNumberish,
    cliffTime: BigNumberish,
    endTime: BigNumberish,
    isRevocable: boolean
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    totalAmount: bigint,
    startTime: bigint,
    cliffTime: bigint,
    endTime: bigint,
    isRevocable: boolean
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    totalAmount: bigint;
    startTime: bigint;
    cliffTime: bigint;
    endTime: bigint;
    isRevocable: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IVestingVault extends BaseContract {
  connect(runner?: ContractRunner | null): IVestingVault;
  waitForDeployment(): Promise<this>;

  interface: IVestingVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateClaimableAmount: TypedContractMethod<
    [scheduleId: BigNumberish],
    [bigint],
    "view"
  >;

  calculateVestedAmount: TypedContractMethod<
    [scheduleId: BigNumberish],
    [bigint],
    "view"
  >;

  claimVestedTokens: TypedContractMethod<
    [scheduleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createVestingSchedule: TypedContractMethod<
    [
      beneficiary: AddressLike,
      totalAmount: BigNumberish,
      cliffDuration: BigNumberish,
      vestingDuration: BigNumberish,
      isRevocable: boolean,
      revoker: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  getVestingSchedule: TypedContractMethod<
    [scheduleId: BigNumberish],
    [IVestingVault.VestingScheduleStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateClaimableAmount"
  ): TypedContractMethod<[scheduleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateVestedAmount"
  ): TypedContractMethod<[scheduleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimVestedTokens"
  ): TypedContractMethod<[scheduleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createVestingSchedule"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      totalAmount: BigNumberish,
      cliffDuration: BigNumberish,
      vestingDuration: BigNumberish,
      isRevocable: boolean,
      revoker: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getVestingSchedule"
  ): TypedContractMethod<
    [scheduleId: BigNumberish],
    [IVestingVault.VestingScheduleStructOutput],
    "view"
  >;

  getEvent(
    key: "TokensClaimed"
  ): TypedContractEvent<
    TokensClaimedEvent.InputTuple,
    TokensClaimedEvent.OutputTuple,
    TokensClaimedEvent.OutputObject
  >;
  getEvent(
    key: "VestingScheduleCreated"
  ): TypedContractEvent<
    VestingScheduleCreatedEvent.InputTuple,
    VestingScheduleCreatedEvent.OutputTuple,
    VestingScheduleCreatedEvent.OutputObject
  >;

  filters: {
    "TokensClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;
    TokensClaimed: TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;

    "VestingScheduleCreated(uint256,address,uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
    VestingScheduleCreated: TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
  };
}
