/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IBonding {
  export type MilestoneStruct = {
    usdcThreshold: BigNumberish;
    price: BigNumberish;
    fvcAllocation: BigNumberish;
    name: string;
    isActive: boolean;
  };

  export type MilestoneStructOutput = [
    usdcThreshold: bigint,
    price: bigint,
    fvcAllocation: bigint,
    name: string,
    isActive: boolean
  ] & {
    usdcThreshold: bigint;
    price: bigint;
    fvcAllocation: bigint;
    name: string;
    isActive: boolean;
  };

  export type VestingScheduleStruct = {
    amount: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
  };

  export type VestingScheduleStructOutput = [
    amount: bigint,
    startTime: bigint,
    endTime: bigint
  ] & { amount: bigint; startTime: bigint; endTime: bigint };
}

export interface BondingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BONDING_MANAGER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_WALLET_CAP"
      | "TOTAL_FVC_ALLOCATION"
      | "TOTAL_SALE_TARGET"
      | "UPGRADER_ROLE"
      | "allocateFVC"
      | "allocateFVCToMilestone"
      | "bond"
      | "calculateFVCAmount"
      | "calculateUSDCAmount"
      | "completeCurrentRound"
      | "currentMilestone"
      | "endPrivateSale"
      | "fvc"
      | "getAllMilestones"
      | "getCurrentDiscount"
      | "getCurrentMilestone"
      | "getCurrentPrice"
      | "getCurrentRound"
      | "getNextMilestone"
      | "getRemainingFVC"
      | "getRoleAdmin"
      | "getSaleProgress"
      | "getVestedAmount"
      | "getVestingSchedule"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isLocked"
      | "markPublicLaunch"
      | "milestones"
      | "privateSaleActive"
      | "proxiableUUID"
      | "renounceRole"
      | "revokeRole"
      | "saleEndTime"
      | "saleStartTime"
      | "startNextRound"
      | "startPrivateSale"
      | "supportsInterface"
      | "totalBonded"
      | "totalFVCSold"
      | "treasury"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "usdc"
      | "userBonded"
      | "vestingSchedules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "BeaconUpgraded"
      | "Bonded"
      | "FVCAllocated"
      | "Initialized"
      | "MilestoneReached"
      | "PrivateSaleEnded"
      | "PrivateSaleStarted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Upgraded"
      | "VestingScheduleCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BONDING_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_WALLET_CAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_FVC_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_SALE_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocateFVC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allocateFVCToMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "bond", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "calculateFVCAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateUSDCAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeCurrentRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentMilestone",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "endPrivateSale",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fvc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllMilestones",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentDiscount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMilestone",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNextMilestone",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingFVC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleProgress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVestedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingSchedule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isLocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markPublicLaunch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "privateSaleActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "saleEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "saleStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startNextRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startPrivateSale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBonded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFVCSold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBonded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingSchedules",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BONDING_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_WALLET_CAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_FVC_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_SALE_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateFVC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateFVCToMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateFVCAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateUSDCAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeCurrentRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endPrivateSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fvc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingFVC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSaleProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isLocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markPublicLaunch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "privateSaleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "saleEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saleStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startNextRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startPrivateSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBonded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFVCSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userBonded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vestingSchedules",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondedEvent {
  export type InputTuple = [
    user: AddressLike,
    usdcAmount: BigNumberish,
    fvcAmount: BigNumberish,
    milestoneIndex: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    usdcAmount: bigint,
    fvcAmount: bigint,
    milestoneIndex: bigint
  ];
  export interface OutputObject {
    user: string;
    usdcAmount: bigint;
    fvcAmount: bigint;
    milestoneIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FVCAllocatedEvent {
  export type InputTuple = [milestoneIndex: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [milestoneIndex: bigint, amount: bigint];
  export interface OutputObject {
    milestoneIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneReachedEvent {
  export type InputTuple = [
    milestoneIndex: BigNumberish,
    usdcThreshold: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    milestoneIndex: bigint,
    usdcThreshold: bigint,
    price: bigint
  ];
  export interface OutputObject {
    milestoneIndex: bigint;
    usdcThreshold: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivateSaleEndedEvent {
  export type InputTuple = [
    totalBonded: BigNumberish,
    totalFVCSold: BigNumberish
  ];
  export type OutputTuple = [totalBonded: bigint, totalFVCSold: bigint];
  export interface OutputObject {
    totalBonded: bigint;
    totalFVCSold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivateSaleStartedEvent {
  export type InputTuple = [startTime: BigNumberish, endTime: BigNumberish];
  export type OutputTuple = [startTime: bigint, endTime: bigint];
  export interface OutputObject {
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingScheduleCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Bonding extends BaseContract {
  connect(runner?: ContractRunner | null): Bonding;
  waitForDeployment(): Promise<this>;

  interface: BondingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BONDING_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_WALLET_CAP: TypedContractMethod<[], [bigint], "view">;

  TOTAL_FVC_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  TOTAL_SALE_TARGET: TypedContractMethod<[], [bigint], "view">;

  UPGRADER_ROLE: TypedContractMethod<[], [string], "view">;

  allocateFVC: TypedContractMethod<[arg0: BigNumberish], [void], "view">;

  allocateFVCToMilestone: TypedContractMethod<
    [milestoneIndex: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  bond: TypedContractMethod<[usdcAmount: BigNumberish], [void], "nonpayable">;

  calculateFVCAmount: TypedContractMethod<
    [usdcAmount: BigNumberish],
    [bigint],
    "view"
  >;

  calculateUSDCAmount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  completeCurrentRound: TypedContractMethod<[], [void], "view">;

  currentMilestone: TypedContractMethod<[], [bigint], "view">;

  endPrivateSale: TypedContractMethod<[], [void], "nonpayable">;

  fvc: TypedContractMethod<[], [string], "view">;

  getAllMilestones: TypedContractMethod<
    [],
    [IBonding.MilestoneStructOutput[]],
    "view"
  >;

  getCurrentDiscount: TypedContractMethod<[], [bigint], "view">;

  getCurrentMilestone: TypedContractMethod<
    [],
    [IBonding.MilestoneStructOutput],
    "view"
  >;

  getCurrentPrice: TypedContractMethod<[], [bigint], "view">;

  getCurrentRound: TypedContractMethod<[], [bigint], "view">;

  getNextMilestone: TypedContractMethod<
    [],
    [IBonding.MilestoneStructOutput],
    "view"
  >;

  getRemainingFVC: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSaleProgress: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        progress: bigint;
        currentMilestoneIndex: bigint;
        totalBondedAmount: bigint;
        totalFVCSoldAmount: bigint;
      }
    ],
    "view"
  >;

  getVestedAmount: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { vestedAmount: bigint; totalAmount: bigint }],
    "view"
  >;

  getVestingSchedule: TypedContractMethod<
    [user: AddressLike],
    [IBonding.VestingScheduleStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [_fvc: AddressLike, _usdc: AddressLike, _treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  isLocked: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  markPublicLaunch: TypedContractMethod<[], [void], "view">;

  milestones: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, boolean] & {
        usdcThreshold: bigint;
        price: bigint;
        fvcAllocation: bigint;
        name: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  privateSaleActive: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  saleEndTime: TypedContractMethod<[], [bigint], "view">;

  saleStartTime: TypedContractMethod<[], [bigint], "view">;

  startNextRound: TypedContractMethod<[], [void], "view">;

  startPrivateSale: TypedContractMethod<
    [duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalBonded: TypedContractMethod<[], [bigint], "view">;

  totalFVCSold: TypedContractMethod<[], [bigint], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  userBonded: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  vestingSchedules: TypedContractMethod<
    [user: AddressLike],
    [IBonding.VestingScheduleStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BONDING_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_WALLET_CAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_FVC_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_SALE_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allocateFVC"
  ): TypedContractMethod<[arg0: BigNumberish], [void], "view">;
  getFunction(
    nameOrSignature: "allocateFVCToMilestone"
  ): TypedContractMethod<
    [milestoneIndex: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bond"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateFVCAmount"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateUSDCAmount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "completeCurrentRound"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "currentMilestone"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "endPrivateSale"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fvc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllMilestones"
  ): TypedContractMethod<[], [IBonding.MilestoneStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getCurrentDiscount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentMilestone"
  ): TypedContractMethod<[], [IBonding.MilestoneStructOutput], "view">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNextMilestone"
  ): TypedContractMethod<[], [IBonding.MilestoneStructOutput], "view">;
  getFunction(
    nameOrSignature: "getRemainingFVC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSaleProgress"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        progress: bigint;
        currentMilestoneIndex: bigint;
        totalBondedAmount: bigint;
        totalFVCSoldAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVestedAmount"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { vestedAmount: bigint; totalAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVestingSchedule"
  ): TypedContractMethod<
    [user: AddressLike],
    [IBonding.VestingScheduleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_fvc: AddressLike, _usdc: AddressLike, _treasury: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isLocked"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markPublicLaunch"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, boolean] & {
        usdcThreshold: bigint;
        price: bigint;
        fvcAllocation: bigint;
        name: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "privateSaleActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "saleEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "saleStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "startNextRound"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "startPrivateSale"
  ): TypedContractMethod<[duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalBonded"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFVCSold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userBonded"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "vestingSchedules"
  ): TypedContractMethod<
    [user: AddressLike],
    [IBonding.VestingScheduleStructOutput],
    "view"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Bonded"
  ): TypedContractEvent<
    BondedEvent.InputTuple,
    BondedEvent.OutputTuple,
    BondedEvent.OutputObject
  >;
  getEvent(
    key: "FVCAllocated"
  ): TypedContractEvent<
    FVCAllocatedEvent.InputTuple,
    FVCAllocatedEvent.OutputTuple,
    FVCAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneReached"
  ): TypedContractEvent<
    MilestoneReachedEvent.InputTuple,
    MilestoneReachedEvent.OutputTuple,
    MilestoneReachedEvent.OutputObject
  >;
  getEvent(
    key: "PrivateSaleEnded"
  ): TypedContractEvent<
    PrivateSaleEndedEvent.InputTuple,
    PrivateSaleEndedEvent.OutputTuple,
    PrivateSaleEndedEvent.OutputObject
  >;
  getEvent(
    key: "PrivateSaleStarted"
  ): TypedContractEvent<
    PrivateSaleStartedEvent.InputTuple,
    PrivateSaleStartedEvent.OutputTuple,
    PrivateSaleStartedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "VestingScheduleCreated"
  ): TypedContractEvent<
    VestingScheduleCreatedEvent.InputTuple,
    VestingScheduleCreatedEvent.OutputTuple,
    VestingScheduleCreatedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "Bonded(address,uint256,uint256,uint256)": TypedContractEvent<
      BondedEvent.InputTuple,
      BondedEvent.OutputTuple,
      BondedEvent.OutputObject
    >;
    Bonded: TypedContractEvent<
      BondedEvent.InputTuple,
      BondedEvent.OutputTuple,
      BondedEvent.OutputObject
    >;

    "FVCAllocated(uint256,uint256)": TypedContractEvent<
      FVCAllocatedEvent.InputTuple,
      FVCAllocatedEvent.OutputTuple,
      FVCAllocatedEvent.OutputObject
    >;
    FVCAllocated: TypedContractEvent<
      FVCAllocatedEvent.InputTuple,
      FVCAllocatedEvent.OutputTuple,
      FVCAllocatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MilestoneReached(uint256,uint256,uint256)": TypedContractEvent<
      MilestoneReachedEvent.InputTuple,
      MilestoneReachedEvent.OutputTuple,
      MilestoneReachedEvent.OutputObject
    >;
    MilestoneReached: TypedContractEvent<
      MilestoneReachedEvent.InputTuple,
      MilestoneReachedEvent.OutputTuple,
      MilestoneReachedEvent.OutputObject
    >;

    "PrivateSaleEnded(uint256,uint256)": TypedContractEvent<
      PrivateSaleEndedEvent.InputTuple,
      PrivateSaleEndedEvent.OutputTuple,
      PrivateSaleEndedEvent.OutputObject
    >;
    PrivateSaleEnded: TypedContractEvent<
      PrivateSaleEndedEvent.InputTuple,
      PrivateSaleEndedEvent.OutputTuple,
      PrivateSaleEndedEvent.OutputObject
    >;

    "PrivateSaleStarted(uint256,uint256)": TypedContractEvent<
      PrivateSaleStartedEvent.InputTuple,
      PrivateSaleStartedEvent.OutputTuple,
      PrivateSaleStartedEvent.OutputObject
    >;
    PrivateSaleStarted: TypedContractEvent<
      PrivateSaleStartedEvent.InputTuple,
      PrivateSaleStartedEvent.OutputTuple,
      PrivateSaleStartedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "VestingScheduleCreated(address,uint256,uint256,uint256)": TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
    VestingScheduleCreated: TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
  };
}
