/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Bonding } from "./Bonding";
export type { FVC } from "./FVC";
export type { Staking } from "./Staking";
